### PR TITLE
feat: add product and license support

### PR DESCRIPTION
**Pull request by rmyers808**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3)

### CODE REVIEW

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3)* status: all files reviewed, 2 unresolved discussions (waiting on @rmyers808)

___
*[examples/run-aion-labserver/main.tf, line 1 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3#-MdJzZXgEJBn6jDrG-gE:-MdJzZXgEJBn6jDrG-gF:b-828e7q) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-aion/blob/5d3289227c6456bce104684802f9339fde39ef0a/examples/run-aion-labserver/main.tf#L1)):*
> ```HCL
> ## Example : This Terraform module deploys Spirent TestCenter Virtual Machines from OVF template.
> ```

Need up update this description for LabServer
___
*[examples/run-aion-labserver/variable.tf, line 39 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3#-MdK-6vu9BCr4QTniefV:-MdK-6vu9BCr4QTniefW:bp5vbmk) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-aion/blob/5d3289227c6456bce104684802f9339fde39ef0a/examples/run-aion-labserver/variable.tf#L39)):*
> ```HCL
> variable "num_cpus" {
>   description = "Number of virtual processor cores assigned to an instance"
>   default     = "2"
> ```

Suggest going with default resource requirements mentioned in our Spirent User Guide for LabServer.
- 4 core CPU
- 32 GB RAM
- 500 GB disk (SSD or better)

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @jhiga)

___
*[examples/run-aion-labserver/main.tf, line 1 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3#-MdJzZXgEJBn6jDrG-gE:-MdLkOAo7ysF5sqIp4NS:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-aion/blob/5d3289227c6456bce104684802f9339fde39ef0a/examples/run-aion-labserver/main.tf#L1)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Need up update this description for LabServer
</blockquote></details>

Done.
___
*[examples/run-aion-labserver/variable.tf, line 39 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3#-MdK-6vu9BCr4QTniefV:-MdLkRkdAuNr9ULRy0q7:bhp7g75) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-aion/blob/5d3289227c6456bce104684802f9339fde39ef0a/examples/run-aion-labserver/variable.tf#L39)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Suggest going with default resource requirements mentioned in our Spirent User Guide for LabServer.
- 4 core CPU
- 32 GB RAM
- 500 GB disk (SSD or better)
</blockquote></details>

Done.   Tested on virttest and worked okay.

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3)* status: all files reviewed, 1 unresolved discussion (waiting on @rmyers808)

___
*[examples/run-aion-labserver/main.tf, line 1 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3#-MdJzZXgEJBn6jDrG-gE:-MdNLYpK9e_ymE0STRoE:b-jvhuv9) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-aion/blob/5d3289227c6456bce104684802f9339fde39ef0a/examples/run-aion-labserver/main.tf#L1)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you need to remove the part about "deployed Spirent TestCenter Virtual Machines from OVF template".  This example just deploys the LabServer and adds entitlements.

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @jhiga)

___
*[examples/run-aion-labserver/main.tf, line 1 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3#-MdJzZXgEJBn6jDrG-gE:-MdOYGHX2OzrsDpQpaFE:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-aion/blob/5d3289227c6456bce104684802f9339fde39ef0a/examples/run-aion-labserver/main.tf#L1)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

I think you need to remove the part about "deployed Spirent TestCenter Virtual Machines from OVF template".  This example just deploys the LabServer and adds entitlements.
</blockquote></details>

Done.

**Review by jhiga — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/3#-:-MdOYZDpBzcCd0UJjBLp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rmyers808)

**Pull request merged**
