### PR TITLE
vSphere AION with static ips

### PR DESCRIPTION
**Pull request by rmyers808**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/1)

### CODE REVIEW

**Review by jhiga — CHANGES_REQUESTED** [review]
Will this script only work if static IPs are used?  What if they have DHCP?

> Reviewed 1 of 11 files at r1, 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/1#-:-MUGT5sYD7G9W48ScH97:bsuktbf)* status: all files reviewed, 1 unresolved discussion (waiting on @radhikabhat08 and @rmyers808)

___
*[geniso.sh, line 1 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/1#-MUGQ0730xFvlQBxcFAj:-MUGQ074BzZrWmRR72HW:b-celwve) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-aion/blob/2e79f645bc5dc641d9876b2d91ebdbe21923c7ff/geniso.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

did you run this through `shellcheck`?

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/1)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @jhiga and @radhikabhat08)

___
*[geniso.sh, line 1 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/1#-MUGQ0730xFvlQBxcFAj:-MUH-5Rh2pJRGGGu0YU8:b93htar) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-aion/blob/2e79f645bc5dc641d9876b2d91ebdbe21923c7ff/geniso.sh#L1)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

did you run this through `shellcheck`?
</blockquote></details>

No, I hadn't used that before.  Checked in fixes.

**Comment by jhiga** [comment]
Please use changes to README from https://github.com/Spirent-Terraform-Modules/terraform-aws-aion/pull/3

**Review by jhiga — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-aion/1#-:-MUK9-8F4i8c2xksznQY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @radhikabhat08)

**Pull request merged**
